service: backend-shop
frameworkVersion: '3'

plugins:
    - serverless-plugin-typescript
    - serverless-offline
    - serverless-dynamodb-local

provider:
    name: aws
    runtime: nodejs16.x
    stage: dev
    profile: kavi
    region: eu-central-1
    environment:
        CARS_TABLE_NAME: kavi-shop-cars
    iam:
        role:
            permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'
            statements:
                - Effect: 'Allow'
                  Action:
                      - 'dynamodb:*'
                      - 's3:*'
                  Resource: '*'

custom:
    dynamodb:
        stages:
            - dev
        start:
            port: 8000
            inMemory: true
            migrate: true
        migration:
            dir: offline/migrations

functions:
    getCarList:
        handler: src/handlers/cars/getCarList.handler
        events:
            - http:
                  path: cars
                  method: get
                  cors: true
    createNewCar:
        handler: src/handlers/cars/createNewCar.handler
        events:
            - http:
                  path: cars
                  method: post
                  cors: true
    getCarById:
        handler: src/handlers/cars/getCarById.handler
        events:
            - http:
                  path: cars/{id}
                  method: get
                  cors: true
                  request:
                      parameters:
                          paths:
                              id: true
resources:
    Resources:
        CarsDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:provider.environment.CARS_TABLE_NAME}
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                