service: backend-shop
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  profile: kavi
  region: eu-central-1
  iam:
    role: arn:aws:iam::398158581759:role/BasicLambdaExecutionRole

functions:
  getCarList:
    handler: src/handlers/cars/getCarList.handler
    events:
       - http:
          path: cars
          method: get
          cors: true
  getCarById:
    handler: src/handlers/cars/getCarById.handler
    events:
      - http:
          path: cars/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true