service: authorization-service
frameworkVersion: '3'

plugins:
    - serverless-plugin-typescript
    - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  profile: kavi
  region: eu-central-1
  apiGateway:
      minimumCompressionSize: 1024
      shouldStartNameWithService: true
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
      LOGIN: process.env.LOGIN
      PASSWORD: process.env.PASSWORD
  iam:
      role:
          permissionsBoundary: 'arn:aws:iam::${aws:accountId}:policy/eo_role_boundary'

functions:
  basicAuthorizer:
    handler: src/handlers/basicAuthorizer.handler
resources:
  Outputs:
    basicAuthorizerARN:
      Value:
        'Fn::GetAtt':
          - BasicAuthorizerLambdaFunction
          - Arn